name = "configurator"name = "configurator"

compatibility_date = "2025-03-25"pages_build_output_dir = ".open-next/assets"

compatibility_flags = ["nodejs_compat"]compatibility_date = "2025-03-25"

compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run pages:build"

[build.upload]
format = "service-worker"
